### ISSUE TITLE
Unable to Omit elements that are renamed 

### ISSUE THREAD

**Issue by Chorjo** [BillyRuffian/faker_maker#36]
I have a situation where I am renaming an element due to the snake casing/Camel casing standard, as below. I am trying to omit this renamed element but it doesn't, it changes the value to null instead. 

`
FM.factory :environment do 
    test_env(json: 'testEnvironment', omit: :nil) { 'qa1' }
    ...
    ...
end

FM[:environment].build(test_env: nil)
# { 'testEnvironment': null }
`

**Comment by BillyRuffian** [comment]
@Chorjo this is fixed in 1.1.5
